/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package investigacionoperaciones;


import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import static investigacionoperaciones.pantalla.wax;
import static investigacionoperaciones.pantalla.Nen;
import static investigacionoperaciones.pantalla.Nes;
import static investigacionoperaciones.pantalla.Ne;
import static investigacionoperaciones.pantalla.intd;
import static investigacionoperaciones.pantalla.mayor;
import static investigacionoperaciones.pantalla.demandaZ;
import static investigacionoperaciones.pantalla.TentregaZ;
import static investigacionoperaciones.pantalla.TesperaZ;
import static investigacionoperaciones.pantalla.auxivar;

/**
 *
 * @author AdolfoManuel
 */
public class Pantalla_desicion extends javax.swing.JFrame {


private void wax_ini(){
    for(int i=0;i<11;i++)
    wax[i] = "";
    
    // ...
}

public static int contarPalabras(String s) {
    int contador = 1, pos;
    s = s.trim(); //eliminar los posibles espacios en blanco al principio y al final
    if (s.isEmpty()) { //si la cadena está vacía
        contador = 0;
    } else {
                pos = s.indexOf(","); //se busca el primer espacio en blanco
                while (pos != -1) { //mientras que se encuentre un espacio en blanco
                           contador++; //se cuenta una palabra
                           pos = s.indexOf(",", pos + 1); //se busca el siguiente espacio en blanco
                }                                               //a continuación del actual
    }
    return contador;
}

    public String leer(String nombre){

//El parametro nombre indica el nombre del archivo por ejemplo "prueba.txt"



    try{

    File f;
    FileReader lectorArchivo;
    //Creamos el objeto del archivo que vamos a leer

    f = new File(nombre);

    //Creamos el objeto FileReader que abrira el flujo(Stream) de datos para realizar la lectura
    lectorArchivo = new FileReader(f);
    //Creamos un lector en buffer para recopilar datos a travez del flujo "lectorArchivo" que hemos creado
    BufferedReader br = new BufferedReader(lectorArchivo);
    String l="";
   
    //Esta variable "l" la utilizamos para guardar mas adelante toda la lectura del archivo
    String aux="";/*variable auxiliar*/
    int i=0;
    while(true){
    //este ciclo while se usa para repetir el proceso de lectura, ya que se lee solo 1 linea de texto a la vez
   
    aux=br.readLine();
    
    //leemos una linea de texto y la guardamos en la variable auxiliar
    
    if(aux!=null){
        //wax[i]=aux;
    wax[i]=aux;i++;
    }
     
    /*si la variable aux tiene datos se va acumulando en la variable l,
    * en caso de ser nula quiere decir que ya nos hemos leido todo
    * el archivo de texto*/
    else
    break;
    }
    br.close();
    lectorArchivo.close();
    return l;
    }catch(IOException e){
    System.out.println("Error:"+e.getMessage());
    }

    return null;

    }
    /**
     * Creates new form Pantalla_desicion
     */
    public Pantalla_desicion() {
        initComponents();
        wax_ini();
     //  new  Pantalla_desicion().setVisible(true);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Simulacion de modelo de Inventario");

        jButton1.setText("Inicializar por Pantalla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Inicializar por Archivo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Escoja como se inicializaran los datos de la simulacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel2)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        ingresarDatos ingreso = new ingresarDatos();
        this.setVisible(false);
       
        ingreso.setVisible(true);
   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     javax.swing.JFileChooser j= new javax.swing.JFileChooser();
     j.showOpenDialog(j);
     String path= j.getSelectedFile().getAbsolutePath();
     leer(path);  // TODO add your handling code here:
   // System.out.print(wax[1]);
    //System.out.print(wax[4]);
    System.out.print(wax[10]);
    
   
    
   //System.out.print(contarPalabras(wax[1]));
   //System.out.print(contarPalabras(wax[4]));
   //System.out.print(contarPalabras(wax[16]));
    
        intd = contarPalabras(wax[1]);
        Nen = contarPalabras(wax[4]);
        Nes = contarPalabras(wax[7]);
        Ne=Integer.parseInt(wax[10]);
        auxivar[0]=wax[12];
        auxivar[1]=wax[14];
        auxivar[2]=wax[16];
        auxivar[3]=wax[18];
        auxivar[4]=wax[20];        
        //Ne = s4t1.countTokens(); 
        if(intd > Nen)
                        if(intd>Nes) 
                            mayor=intd;
                        else
                            mayor=Nes;
                    else if(Nen>Nes)
                        mayor=Nen;
                        else
                            mayor=Nes;
        
        
        
    String cadena1 = wax[1],delimitadores1=",";
    String[] temp1 = cadena1.split(delimitadores1);
    
    String cadena2 = wax[2],delimitadores2=",";
    String[] temp2 = cadena2.split(delimitadores2);
    
    String cadena3 = wax[4],delimitadores3=",";
    String[] temp3 = cadena3.split(delimitadores3);
    
    String cadena4 = wax[5],delimitadores4=",";
    String[] temp4 = cadena4.split(delimitadores4);
    
    String cadena5 = wax[7],delimitadores5=",";
    String[] temp5 = cadena5.split(delimitadores5);
    
    String cadena6 = wax[8],delimitadores6=",";
    String[] temp6 = cadena6.split(delimitadores6);
   
    for (int i=0;i<intd;i++){
        demandaZ[i][0]=temp1[i];
    }
    
    for (int i=0;i<intd;i++){
        demandaZ[i][1]=temp2[i];
    }
    
    for (int i=0;i<Nen;i++){
        TentregaZ[i][0]=temp3[i];
    } 
    
    for (int i=0;i<Nen;i++){
        TentregaZ[i][1]=temp4[i];
    }
     
    for (int i=0;i<Nes;i++){
        TesperaZ[i][0]=temp5[i];
    } 
    
    for (int i=0;i<Nes;i++){
        TesperaZ[i][1]=temp6[i];
    }
     
    
    pantalla pantalla = new pantalla();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_desicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_desicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_desicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_desicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_desicion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
